platform :ios, '8.0'
target ’Douban’ do
pod 'SDWebImage', '~> 3.8.1’
pod 'MBProgressHUD', '~> 0.9.2’
pod 'Masonry', '~> 1.0.1'
pod 'BaiduMapKit', '~> 3.0.0'
pod 'UMengSocialCOM', '~> 5.2.1’
pod 'AFNetworking', '~> 3.1.0'
end
